version: "2"

# checks:
#  return-statements:
#    enabled: false
#  similar-code:
#    enabled: false
#  identical-code:
#    enabled: false
#  file-lines:
#    enabled: false

exclude_paths:
- "UI/"
- "coverage/"
- "server/docs"
- "server/tests"
- ".nyc_output/"
- "node_modules/"
- "server/src/models"
- "server/src/seeders"
- "server/src/migrations"
- "server/src/validations"
- "server/src/dummyControllers"
